// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Todo struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	Completed bool   `json:"completed"`
}
