version: '3'

services:
  mongo:
    image: mongo
    container_name: todo_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - todo_mongo_data:/data/db


volumes:
  todo_mongo_data: { }
