version: "3"

services:
  postgres:
    container_name: app_db
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - appdb_data:/var/lib/postgresql/data

volumes:
  appdb_data: {}
